import{loadQueries,createQuery,updateQuery,deleteQuery}from'./QueryManager.js';
import{COCO_CLASSES}from'../cv/ObjectDetector.js';
const COLORS=['rouge','orange','jaune','vert','cyan','bleu','violet','rose','blanc','gris','noir'];
let _upd=null,_cv=null;
export function initQueryPanel(onUpdate,cvEngine){_upd=onUpdate;_cv=cvEngine;document.getElementById('btn-add-query')?.addEventListener('click',()=>openEditor(null));document.getElementById('btn-add-query-mobile')?.addEventListener('click',()=>openEditor(null));renderQueryList();}
export function renderQueryList(){['query-list','query-list-mobile'].forEach(id=>{const el=document.getElementById(id);if(!el) return;const qs=loadQueries();el.innerHTML=qs.length?qs.map(qrow).join(''):'<p style="padding:12px;font-size:12px;color:var(--text-3)">Aucune requete</p>';el.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEditor(b.dataset.edit)));el.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{deleteQuery(b.dataset.del);renderQueryList();_upd?.();}));el.querySelectorAll('[data-tog]').forEach(inp=>inp.addEventListener('change',()=>{updateQuery(inp.dataset.tog,{enabled:inp.checked});_upd?.();}));});}
function qrow(q){return'<div class="query-row"><label class="toggle" style="flex-shrink:0"><input type="checkbox" data-tog="'+q.id+'" '+(q.enabled?'checked':'')+'/><span class="toggle__slider"></span></label><span class="query-row__name">'+q.name+'</span><span class="query-row__criteria">'+(q.criteria?.length||0)+' crit.</span><button class="btn btn--ghost btn--sm" data-edit="'+q.id+'">Edit</button><button class="btn btn--ghost btn--sm" data-del="'+q.id+'">Del</button></div>';}
function ch(c,coco,cols){let inner='';if(c.type==='object') inner='<select class="select-sm" name="value" style="flex:1">'+coco+'</select>';else if(c.type==='color') inner='<select class="select-sm" name="value">'+cols+'</select><input class="input" name="tolerance" type="number" min="0" max="60" value="'+(c.tolerance||30)+'" style="width:60px"/>';else if(c.type==='face') inner='<span style="font-size:11px;flex:1">Ref:'+(c.refId||'?')+'</span><input type="file" class="input" name="refImg" accept="image/*" style="font-size:11px"/><input class="input" name="distance" type="number" min="0.1" max="1" step="0.05" value="'+(c.distance||0.6)+'" style="width:65px"/>';else if(c.type==='plate') inner='<input class="input" name="value" placeholder="AA-123-BB" value="'+(c.value||'')+'" style="flex:1"/><select class="select-sm" name="mode"><option value="exact">Exact</option><option value="partial">Partiel</option><option value="regex">Regex</option></select>';return'<div class="criterion-row" data-type="'+c.type+'"><span class="criterion-type">['+c.type+']</span>'+inner+'<button class="btn btn--ghost btn--sm" data-rm>&times;</button></div>';}
export function openEditor(qid){const q=qid?loadQueries().find(r=>r.id===qid):null;const modal=document.getElementById('query-modal');if(!modal) return;const coco=COCO_CLASSES.map(cl=>'<option value="'+cl+'">'+cl+'</option>').join('');const cols=COLORS.map(cl=>'<option value="'+cl+'">'+cl+'</option>').join('');modal.innerHTML='<div class="modal"><div class="modal__header"><h3>'+(q?'Editer':'Nouvelle')+' requete</h3><button class="btn btn--ghost btn--sm" id="qe-x">&times;</button></div><div class="modal__body"><div class="settings-row"><label>Nom</label><input class="input" id="qe-name" value="'+(q?.name||'')+'" placeholder="Ex: Camionnette rouge"/></div><div class="settings-row"><label>Confiance (%)</label><input class="input" type="number" min="10" max="100" id="qe-conf" value="'+Math.round((q?.confidenceThreshold||0.7)*100)+'"/></div><div class="settings-row"><label>Capturer frame</label><label class="toggle"><input type="checkbox" id="qe-cap" '+(q?.captureFrameOnMatch!==false?'checked':'')+'/><span class="toggle__slider"></span></label></div><div class="settings-section__title" style="margin-top:12px">Criteres (ET)</div><div id="qe-crit">'+(q?.criteria||[]).map(c=>ch(c,coco,cols)).join('')+'</div><div style="display:flex;gap:6px;margin-top:8px;flex-wrap:wrap"><button class="btn btn--ghost btn--sm" data-add="object">+ Objet</button><button class="btn btn--ghost btn--sm" data-add="color">+ Couleur</button><button class="btn btn--ghost btn--sm" data-add="face">+ Visage</button><button class="btn btn--ghost btn--sm" data-add="plate">+ Plaque</button></div></div><div class="modal__footer"><button class="btn btn--ghost btn--sm" id="qe-cancel">Annuler</button><button class="btn btn--primary btn--sm" id="qe-save">Enregistrer</button></div></div>';modal.classList.remove('hidden');_bind(q,coco,cols);}
function _bind(existing,coco,cols){const $=id=>document.getElementById(id);const close=()=>document.getElementById('query-modal').classList.add('hidden');$('qe-x')?.addEventListener('click',close);$('qe-cancel')?.addEventListener('click',close);document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{const d=document.createElement('div');d.innerHTML=ch({type:b.dataset.add,value:'',mode:'exact',confidence:0.5,tolerance:30,distance:0.6},coco,cols);document.getElementById('qe-crit').appendChild(d.firstElementChild);_brm();}));_brm();$('qe-save')?.addEventListener('click',async()=>{const name=$('qe-name')?.value?.trim()||'Requete',conf=+($('qe-conf')?.value||70)/100,cap=$('qe-cap')?.checked??true,criteria=[];for(const row of document.querySelectorAll('.criterion-row')){const type=row.dataset.type,c={type};row.querySelectorAll('[name]').forEach(el=>{c[el.name]=el.type==='number'?+el.value:el.value;});if(type==='face'){const fi=row.querySelector('[name="refImg"]');if(fi?.files?.[0]){c.refId='face_'+Date.now();const img=await fi2img(fi.files[0]);const ok=await _cv?.addFaceRef(c.refId,img);if(!ok){alert('Aucun visage detecte.');return;}}else c.refId=existing?.criteria?.find(cr=>cr.type==='face')?.refId||null;}criteria.push(c);}if(existing) updateQuery(existing.id,{name,confidenceThreshold:conf,captureFrameOnMatch:cap,criteria});else createQuery({name,confidenceThreshold:conf,captureFrameOnMatch:cap,criteria});close();renderQueryList();_upd?.();});}
function _brm(){document.querySelectorAll('[data-rm]').forEach(b=>{b.onclick=()=>b.closest('.criterion-row').remove();});}
function fi2img(file){return new Promise(ok=>{const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);ok(img);};img.src=u;});}
